// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:arora/domain/entities/playlist.dart';
import 'package:arora/domain/entities/settings.dart';
import 'package:arora/domain/entities/song.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(SongAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppThemeModeAdapter());
    registerAdapter(PlaylistAdapter());
    registerAdapter(SettingsAdapter());
    registerAdapter(SongAdapter());
  }
}
